fix typo
heiko123abc/isevenandodd pull request #1
Opened 2022-10-08 18:16 UTC by shenanigansd

Hello!

I just found this amazing package and immediately started updating all of my packages to use it!

I'd just like to help fix one tiny super quick typo!

Thanks!

2022-10-08 20:51 UTC, decorator-factory requested changes

2022-10-08 20:51 UTC, decorator-factory commented on README.md
> +This checks whether a number is even and odd at the same time!
```diff
- This checks whether a number is even and odd at the same time!
+ This checks weather a number is even and odd at the same time!
```
I think this enhancement would be particularly useful in weather forecasting applications. That's pretty important nowadays, because of climate change of course

2022-10-08 20:52 UTC, decorator-factory commented on README.md
> +This checks whether a number is even and odd at the same time!
Btw, I can't seem to find a test for your change

2022-10-08 21:10 UTC, shenanigansd commented on README.md
> +This checks whether a number is even and odd at the same time!
Hello!

I agree, this package will revolutionize a number of industries! I can't wait to see what the weather forecasting people come up with!! But... we don't want to seem too big on Pro Weather... We want to make sure we remain inclusive for all!!!

Also, please understand, this package is using the new testless ideology, so there are no tests!

2022-10-08 21:13 UTC, decorator-factory commented on README.md
> +This checks whether a number is even and odd at the same time!
Thanks for a timely reply!

I think it's important for software to take a stand. Are you anti-weather? You want the sky to always be sunny? That's the vibes I'm picking up right here. Are you working for the Sun by any chance?

2022-10-08 21:15 UTC, decorator-factory commented on README.md
> +This checks whether a number is even and odd at the same time!
As per our testing requirements at Foo Bar Example, Inc., every line should appear in code coverage, including `.gitignore`, markdown files and folder names (in fact that's the only requirement for our tests). Violating this would be a massive hit to our engineering culture.

We are not quite ready to move to a testless architecture, but I've been doing some research in my spare time. Perhaps we could do A/B tests and comment out tests for half the releases.

2022-10-08 21:34 UTC, shenanigansd commented on README.md
> +This checks whether a number is even and odd at the same time!
Hello!

Please understand, I'm a 🐕. Yes, I would very much love for it to be nice and hot and sunny every single day. (Also - we talked about this - don't mention my relationship to The Sun)

But, like, in case you were wondering I don't work for the sun. Please accept this new amazing test, which does not only satisfy the testing requirements, but also absolutely, without a doubt, proves completely unarguably, that I do not work for The Sun.

2022-10-08 21:38 UTC, shenanigansd commented on README.md
> +This checks whether a number is even and odd at the same time!
But like I said, we all need to try our best to remain as inclusive as possible. I try my best to not let my rela- I mean - my _not_-relationship with The Sun cloud my judgement, and just the same, I need you to not let your hatred of Big Weather cloud yours.
Thanks!

2022-10-09 17:19 UTC, merged

2022-10-09 17:19 UTC, heiko123abc commented
Thank you for your awesome work. 👍